package com.voicebridge.websocket;

public enum MeetingEventType {
    PARTICIPANT_JOINED,
    PARTICIPANT_LEFT,
    HAND_RAISED,
    QUEUE_UPDATED,
    SPEAKER_APPROVED,
    SPEAKER_REJECTED,
    SPEAKER_STARTED,
    SPEAKER_ENDED,
    MEETING_CLOSED,
    PRESENTATION_STARTED,
    PRESENTATION_STOPPED,
    SLIDE_CHANGED
}
