CREATE TABLE organizers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    email         VARCHAR(180) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_organizers_email UNIQUE (email)
);

CREATE TABLE meetings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_code  VARCHAR(12) NOT NULL,
    title         VARCHAR(150) NOT NULL,
    description   VARCHAR(1000),
    organizer_id  BIGINT NOT NULL,
    status        VARCHAR(20) NOT NULL,
    qr_token      VARCHAR(80) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at    TIMESTAMP NULL,
    ended_at      TIMESTAMP NULL,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_meetings_meeting_code UNIQUE (meeting_code),
    CONSTRAINT uk_meetings_qr_token UNIQUE (qr_token),
    CONSTRAINT fk_meetings_organizer FOREIGN KEY (organizer_id) REFERENCES organizers (id)
);

CREATE INDEX idx_meetings_organizer_id ON meetings (organizer_id);
CREATE INDEX idx_meetings_status ON meetings (status);

CREATE TABLE participants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id    BIGINT NOT NULL,
    name          VARCHAR(80) NOT NULL,
    connection_id VARCHAR(120),
    status        VARCHAR(20) NOT NULL,
    session_token VARCHAR(80) NOT NULL,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    joined_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at       TIMESTAMP NULL,
    last_seen_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participants_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id),
    CONSTRAINT uk_participant_meeting_name UNIQUE (meeting_id, name),
    CONSTRAINT uk_participants_session_token UNIQUE (session_token)
);

CREATE INDEX idx_participants_meeting_id ON participants (meeting_id);
CREATE INDEX idx_participants_meeting_status ON participants (meeting_id, status);

CREATE TABLE speaking_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id     BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    status         VARCHAR(20) NOT NULL,
    queue_position INTEGER NOT NULL,
    requested_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at    TIMESTAMP NULL,
    started_at     TIMESTAMP NULL,
    rejected_at    TIMESTAMP NULL,
    finished_at    TIMESTAMP NULL,
    ended_at       TIMESTAMP NULL,
    CONSTRAINT fk_speaking_requests_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id),
    CONSTRAINT fk_speaking_requests_participant FOREIGN KEY (participant_id) REFERENCES participants (id)
);

CREATE INDEX idx_speaking_requests_meeting_id ON speaking_requests (meeting_id);
CREATE INDEX idx_speaking_requests_participant_id ON speaking_requests (participant_id);
CREATE INDEX idx_speaking_requests_meeting_status ON speaking_requests (meeting_id, status);
CREATE INDEX idx_speaking_requests_meeting_queue ON speaking_requests (meeting_id, queue_position);

CREATE TABLE speaker_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id       BIGINT NOT NULL,
    participant_id   BIGINT NOT NULL,
    started_at       TIMESTAMP NOT NULL,
    ended_at         TIMESTAMP NOT NULL,
    duration_seconds BIGINT NOT NULL,
    end_reason       VARCHAR(30) NOT NULL,
    CONSTRAINT fk_speaker_history_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id),
    CONSTRAINT fk_speaker_history_participant FOREIGN KEY (participant_id) REFERENCES participants (id)
);

CREATE INDEX idx_speaker_history_meeting_id ON speaker_history (meeting_id);
CREATE INDEX idx_speaker_history_participant_id ON speaker_history (participant_id);

CREATE TABLE presentations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id    BIGINT NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    file_type     VARCHAR(40) NOT NULL,
    storage_path  VARCHAR(1000) NOT NULL,
    total_slides  INTEGER NOT NULL,
    current_slide INTEGER NOT NULL,
    uploaded_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_presentations_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id),
    CONSTRAINT ck_presentations_total_slides CHECK (total_slides >= 1),
    CONSTRAINT ck_presentations_current_slide CHECK (current_slide >= 1)
);

CREATE INDEX idx_presentations_meeting_id ON presentations (meeting_id);

CREATE TABLE presentation_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id      BIGINT NOT NULL,
    presentation_id BIGINT NOT NULL,
    current_slide   INTEGER NOT NULL,
    is_presenting   BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_presentation_sessions_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id),
    CONSTRAINT fk_presentation_sessions_presentation FOREIGN KEY (presentation_id) REFERENCES presentations (id),
    CONSTRAINT uk_presentation_sessions_meeting UNIQUE (meeting_id),
    CONSTRAINT ck_presentation_sessions_current_slide CHECK (current_slide >= 1)
);

CREATE INDEX idx_presentation_sessions_presentation_id ON presentation_sessions (presentation_id);
